name: CI

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "10 16 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Update Scripts
        id: update
        run: |

          # Download scripts and trackers
          rm -rf og
          rm -rf "${files[@]}"
          rm -rf trackers.txt
          mkdir og

          curl https://greasyfork.org/scripts/431691-bypass-all-shortlinks/code/Bypass%20All%20Shortlinks.user.js -o "Bypass All Shortlinks.user.js"
          curl https://greasyfork.org/scripts/443888-additional-bypass/code/Additional%20Bypass.user.js -o "Additional Bypass.user.js"

           cp -r *.js og
          
          curl -sS "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt" >> trackers.txt
          curl -sS "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_ip.txt" >> trackers.txt
          curl -sS "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_ws.txt" >> trackers.txt
          curl -sS "https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/all.txt" >> trackers.txt

          # Modify scripts
          perl -w -i -l -p -e 'print "// \@downloadURL https://github.com/rushiranpise/userscripts/raw/main/Bypass%20All%20Shortlinks.user.js" if $. == 3' "Bypass All Shortlinks.user.js"
          perl -w -i -l -p -e 'print "// \@updateURL https://github.com/rushiranpise/userscripts/raw/main/Bypass%20All%20Shortlinks.user.js" if $. == 3' "Bypass All Shortlinks.user.js"
          perl -w -i -l -p -e 'print "// \@downloadURL https://github.com/rushiranpise/userscripts/raw/main/Additional%20Bypass.user.js" if $. == 3' "Additional Bypass.user.js"
          perl -w -i -l -p -e 'print "// \@updateURL https://github.com/rushiranpise/userscripts/raw/main/Additional%20Bypass.user.js" if $. == 3' "Additional Bypass.user.js"

          sed -i -e 's|https://rotator.nurul-huda.sch.id/?url=|https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=|' \
                 -e 's|https://bas.nurul-huda.or.id/?url=|https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=|' \
                 -e 's|rotator.nurul-huda.sch.id|adguardteam.github.io|' \
                 -e 's|free4u.nurul-huda.or.id|adguardteam.github.io|' \
                 -e 's|free4u.nurul-huda.or|adguardteam.github.io|' \
                 -e 's|https://free4u.nurul-huda.or.id/?url=|https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=|' \
                 -e 's|rotator.nurul-huda.sch|adguardteam.github.io|' \
                 -e 's|bas.nurul-huda.or.id|adguardteam.github.io|' \
                 -e 's|autofaucet.dutchycorp.space|adguardteam.github.io|' "Bypass All Shortlinks.user.js"
          
          sed -i -e 's|https://rotator.nurul-huda.sch.id/?url=|https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=|' \
                 -e 's|https://bas.nurul-huda.or.id/?url=|https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=|' \
                 -e 's|rotator.nurul-huda.sch.id|adguardteam.github.io|' \
                 -e 's|free4u.nurul-huda.or.id|adguardteam.github.io|' \
                 -e 's|free4u.nurul-huda.or|adguardteam.github.io|' \
                 -e 's|https://free4u.nurul-huda.or.id/?url=|https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=|' \
                 -e 's|rotator.nurul-huda.sch|adguardteam.github.io|' \
                 -e 's|bas.nurul-huda.or.id|adguardteam.github.io|' \
                 -e 's|autofaucet.dutchycorp.space|adguardteam.github.io|' "Additional Bypass.user.js"


          rm -rf *.user.js.1

          # Configure Git
          git config --global user.email "rushiranpise17@gmail.com"
          git config --global user.name "Rushi Ranpise"
          git config --global color.ui true

          # Commit and push changes
          git status && git add . && git commit -m "Updated Scripts on $(date -u +"%D")" && git push || echo done
