name: CI

on:
  workflow_dispatch:
  push:
  schedule:
    - cron: "10 16 * * *"

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
          
      - name: Update Scripts
        id: update
        run: |
          wget -O "1_download_untouched" https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated/raw/branch/main/1_download_untouched.py
          wget -O "2_generate_includes.py" https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated/raw/branch/main/2_generate_includes.py
          wget -O "3_patch.py" https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated/raw/branch/main/3_patch.py

          sed -i -e 's|https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated|https://github.com/rushiranpise/userscripts|' "2_generate_includes.py"
          sed -i -e 's|https://codeberg.org/Amm0ni4/bypass-all-shortlinks-debloated/raw/branch/main/Bypass_All_Shortlinks.user.js|https://github.com/rushiranpise/userscripts/raw/main/Bypass_All_Shortlinks.user.js|' "3_patch.py"

          python 1_download_untouched.py
          python 2_generate_includes.py
          python 3_patch.py
          
          
      # - name: Update Scripts
      #   id: update
      #   run: |

      #     # Download scripts and trackers
      #     rm -rf og
      #     rm -rf "${files[@]}"
      #     rm -rf trackers.txt
      #     mkdir og

      #     wget -O "Bypass All Shortlinks.user.js" https://greasyfork.org/scripts/431691-bypass-all-shortlinks/code/Bypass%20All%20Shortlinks.user.js
      #     wget -O "Additional Bypass.user.js" https://greasyfork.org/scripts/443888-additional-bypass/code/Additional%20Bypass.user.js 

      #      cp -r *.js og
          
      #     curl -sS "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all.txt" >> trackers.txt
      #     curl -sS "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_ip.txt" >> trackers.txt
      #     curl -sS "https://raw.githubusercontent.com/ngosang/trackerslist/master/trackers_all_ws.txt" >> trackers.txt
      #     curl -sS "https://raw.githubusercontent.com/XIU2/TrackersListCollection/master/all.txt" >> trackers.txt

      #     # Modify scripts
      #     perl -w -i -l -p -e 'print "// \@downloadURL https://github.com/rushiranpise/userscripts/raw/main/Bypass%20All%20Shortlinks.user.js" if $. == 3' "Bypass All Shortlinks.user.js"
      #     perl -w -i -l -p -e 'print "// \@updateURL https://github.com/rushiranpise/userscripts/raw/main/Bypass%20All%20Shortlinks.user.js" if $. == 3' "Bypass All Shortlinks.user.js"
      #     perl -w -i -l -p -e 'print "// \@downloadURL https://github.com/rushiranpise/userscripts/raw/main/Additional%20Bypass.user.js" if $. == 3' "Additional Bypass.user.js"
      #     perl -w -i -l -p -e 'print "// \@updateURL https://github.com/rushiranpise/userscripts/raw/main/Additional%20Bypass.user.js" if $. == 3' "Additional Bypass.user.js"

      #     sed -i -e 's|https://rotator.nurul-huda.sch.id/?url=|https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=|' \
      #            -e 's|https://bas.nurul-huda.or.id/?url=|https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=|' \
      #            -e 's|rotator.nurul-huda.sch.id|adguardteam.github.io|' \
      #            -e 's|free4u.nurul-huda.or.id|adguardteam.github.io|' \
      #            -e 's|free4u.nurul-huda.or|adguardteam.github.io|' \
      #            -e 's|https://free4u.nurul-huda.or.id/?url=|https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=|' \
      #            -e 's|rotator.nurul-huda.sch|adguardteam.github.io|' \
      #            -e 's|bas.nurul-huda.or.id|adguardteam.github.io|' \
      #            -e 's|autofaucet.dutchycorp.space|adguardteam.github.io|' "Bypass All Shortlinks.user.js"
          
      #     sed -i -e 's|https://rotator.nurul-huda.sch.id/?url=|https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=|' \
      #            -e 's|https://bas.nurul-huda.or.id/?url=|https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=|' \
      #            -e 's|rotator.nurul-huda.sch.id|adguardteam.github.io|' \
      #            -e 's|free4u.nurul-huda.or.id|adguardteam.github.io|' \
      #            -e 's|free4u.nurul-huda.or|adguardteam.github.io|' \
      #            -e 's|https://free4u.nurul-huda.or.id/?url=|https://adguardteam.github.io/AnonymousRedirect/redirect.html?url=|' \
      #            -e 's|rotator.nurul-huda.sch|adguardteam.github.io|' \
      #            -e 's|bas.nurul-huda.or.id|adguardteam.github.io|' \
      #            -e 's|autofaucet.dutchycorp.space|adguardteam.github.io|' "Additional Bypass.user.js"


      #     rm -rf *.user.js.1
          
      - name: Push Changes
        id: push
        run: |
          # Configure Git
          git config --global user.email "rushiranpise17@gmail.com"
          git config --global user.name "Rushi Ranpise"
          git config --global color.ui true

          # Commit and push changes
          git status && git add . && git commit -m "Updated Scripts on $(date -u +"%D")" && git push || echo done
